name: Deploy to Firebase Hosting on PR
on: pull_request  # Fixed from pull_request_target
permissions:
  contents: write
  pull-requests: write
  checks: write
  deployments: write

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}  # Ensure correct branch checkout
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0  # Fixed from v1 to v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub Token instead of PAT
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_REACT_FIREBASE_DEPLOYMEN_E0055 }}
          projectId: react-firebase-deploymen-e0055
