name: Deploy to Firebase Hosting on PR
on: pull_request_target  # Change from pull_request to pull_request_target
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}  # Ensure PR branch is checked out
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_REACT_FIREBASE_DEPLOYMEN_E0055 }}
          projectId: react-firebase-deploymen-e0055
